import { Hero } from "./hero"

export const HEROES : Hero[] = [ 
            new Hero(1, 'Fuji', 'Portrait_01.png'),
            new Hero(2, 'Max', 'Portrait_02.png'),
            new Hero(3, 'Haze', 'Portrait_03.png'),
            new Hero(4, 'Bhaama', 'Portrait_04.png'),
            new Hero(5, 'Phaze', 'Portrait_05.png'),
            new Hero(6, 'Luca', 'Portrait_06.png'),
            new Hero(7, 'Ammasarah', 'Portrait_07.png'),
            new Hero(8, 'Slick', 'Portrait_08.png'),
            new Hero(9, 'Shan', 'Portrait_09.png'),
            new Hero(10, 'Pfferra', 'Portrait_10.png'),

            new Hero(11, 'Nicomarra', 'Portrait_11.png'),
            new Hero(12, 'Plaan', 'Portrait_12.png'),
            new Hero(13, 'Sil', 'Portrait_13.png'),
            new Hero(14, 'Macarah', 'Portrait_14.png'),
            new Hero(15, 'Samma', 'Portrait_15.png'),
            new Hero(16, 'T\'Chiara', 'Portrait_16.png'),
            new Hero(17, 'Riccar', 'Portrait_17.png'),
            new Hero(18, 'Emapha', 'Portrait_18.png'),
            new Hero(19, 'Qin', 'Portrait_19.png'),
            new Hero(20, 'Qin', 'Portrait_20.png'),
           
            new Hero(21, 'Nicomarra', 'Portrait_21.png'),
            new Hero(22, 'Plaan', 'Portrait_22.png'),
            new Hero(23, 'Sil', 'Portrait_23.png'),
            new Hero(24, 'Macarah', 'Portrait_24.png'),
            new Hero(25, 'Samma', 'Portrait_25.png'),
            new Hero(26, 'T\'Chiara', 'Portrait_26.png'),
            new Hero(27, 'Riccar', 'Portrait_27.png'),
            new Hero(28, 'Emapha', 'Portrait_28.png'),
            new Hero(29, 'Qin', 'Portrait_29.png'),
            new Hero(30, 'Qin', 'Portrait_30.png'),
            
            new Hero(31, 'Nicomarra', 'Portrait_31.png'),
            new Hero(32, 'Plaan', 'Portrait_32.png'),
            new Hero(33, 'Sil', 'Portrait_33.png'),
            new Hero(34, 'Macarah', 'Portrait_34.png'),
            new Hero(35, 'Samma', 'Portrait_35.png'),
            new Hero(36, 'T\'Chiara', 'Portrait_36.png'),
            new Hero(37, 'Riccar', 'Portrait_37.png'),
            new Hero(38, 'Emapha', 'Portrait_38.png'),
            new Hero(39, 'Qin', 'Portrait_39.png'),
            new Hero(40, 'Qin', 'Portrait_40.png'), 
         
            new Hero(41, 'Nicomarra', 'Portrait_41.png'),
            new Hero(42, 'Plaan', 'Portrait_42.png'),
            new Hero(43, 'Sil', 'Portrait_43.png'),
            new Hero(44, 'Macarah', 'Portrait_44.png'),
            new Hero(45, 'Samma', 'Portrait_45.png'),
            new Hero(46, 'T\'Chiara', 'Portrait_46.png'),
            new Hero(47, 'Riccar', 'Portrait_47.png'),
            new Hero(48, 'Emapha', 'Portrait_48.png'),
            new Hero(49, 'Qin', 'Portrait_49.png'),
            new Hero(50, 'Qin', 'Portrait_50.png'), 
    ];